In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

In [2]:
train=pd.read_csv("data/train_bike.csv", parse_dates=["datetime"])
train.shape
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
datetime      10886 non-null datetime64[ns]
season        10886 non-null int64
holiday       10886 non-null int64
workingday    10886 non-null int64
weather       10886 non-null int64
temp          10886 non-null float64
atemp         10886 non-null float64
humidity      10886 non-null int64
windspeed     10886 non-null float64
casual        10886 non-null int64
registered    10886 non-null int64
count         10886 non-null int64
dtypes: datetime64[ns](1), float64(3), int64(8)
memory usage: 1020.6 KB

In [4]:
test=pd.read_csv("data/test_bike.csv", parse_dates=["datetime"])
test.shape
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6493 entries, 0 to 6492
Data columns (total 9 columns):
datetime      6493 non-null datetime64[ns]
season        6493 non-null int64
holiday       6493 non-null int64
workingday    6493 non-null int64
weather       6493 non-null int64
temp          6493 non-null float64
atemp         6493 non-null float64
humidity      6493 non-null int64
windspeed     6493 non-null float64
dtypes: datetime64[ns](1), float64(3), int64(5)
memory usage: 456.6 KB

In [6]:
train['year']=train['datetime'].dt.year
train['month']=train['datetime'].dt.month
train['hour']=train['datetime'].dt.hour
train['dayofweek']=train['datetime'].dt.dayofweek
train.shape
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 16 columns):
datetime      10886 non-null datetime64[ns]
season        10886 non-null int64
holiday       10886 non-null int64
workingday    10886 non-null int64
weather       10886 non-null int64
temp          10886 non-null float64
atemp         10886 non-null float64
humidity      10886 non-null int64
windspeed     10886 non-null float64
casual        10886 non-null int64
registered    10886 non-null int64
count         10886 non-null int64
year          10886 non-null int64
month         10886 non-null int64
hour          10886 non-null int64
dayofweek     10886 non-null int64
dtypes: datetime64[ns](1), float64(3), int64(12)
memory usage: 1.3 MB

In [7]:
test['year']=test['datetime'].dt.year
test['month']=test['datetime'].dt.month
test['hour']=test['datetime'].dt.hour
test['dayofweek']=test['datetime'].dt.dayofweek
test.shape
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6493 entries, 0 to 6492
Data columns (total 13 columns):
datetime      6493 non-null datetime64[ns]
season        6493 non-null int64
holiday       6493 non-null int64
workingday    6493 non-null int64
weather       6493 non-null int64
temp          6493 non-null float64
atemp         6493 non-null float64
humidity      6493 non-null int64
windspeed     6493 non-null float64
year          6493 non-null int64
month         6493 non-null int64
hour          6493 non-null int64
dayofweek     6493 non-null int64
dtypes: datetime64[ns](1), float64(3), int64(9)
memory usage: 659.5 KB

In [12]:
# 범주형(category)
train['season']=train['season'].astype('category')
test['season']=test['season'].astype('category')

fn=['season', 'holiday', 'workingday', 'weather']
for f in fn:
    train[f]=train[f].astype('category')
    test[f]=test[f].astype('category')
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 16 columns):
datetime      10886 non-null datetime64[ns]
season        10886 non-null category
holiday       10886 non-null category
workingday    10886 non-null category
weather       10886 non-null category
temp          10886 non-null float64
atemp         10886 non-null float64
humidity      10886 non-null int64
windspeed     10886 non-null float64
casual        10886 non-null int64
registered    10886 non-null int64
count         10886 non-null int64
year          10886 non-null int64
month         10886 non-null int64
hour          10886 non-null int64
dayofweek     10886 non-null int64
dtypes: category(4), datetime64[ns](1), float64(3), int64(8)
memory usage: 1.0 MB

In [13]:
from sklearn.ensemble import RandomForestRegressor

In [19]:
rf_wind=RandomForestRegressor()
fcolumns=['season', 'weather', 'humidity', 'month', 'temp', 'year', 'hour', 'dayofweek', 'atemp']
xtrain=train[fcolumns]
xtrain
yrlabel=train['registered']
yclabel=train['casual']

# rfModel=RandomForestRegressor() 
# rfModel.fit()

In [20]:
yrlabel

0         13
1         32
2         27
3         10
4          1
5          1
6          0
7          2
8          7
9          6
10        24
11        30
12        55
13        47
14        71
15        70
16        52
17        52
18        26
19        31
20        25
21        31
22        17
23        24
24        13
25        16
26         8
27         4
28         1
29         2
        ...
10856    512
10857    334
10858    264
10859    159
10860    127
10861     80
10862     35
10863     14
10864      2
10865      5
10866      6
10867     29
10868    109
10869    360
10870    665
10871    309
10872    147
10873    169
10874    203
10875    183
10876    185
10877    209
10878    297
10879    536
10880    546
10881    329
10882    231
10883    164
10884    117
10885     84
Name: registered, Length: 10886, dtype: int64

In [22]:
xtest=test[fcolumns]
xtest.shape

(6493, 9)

In [28]:
rfmodel=RandomForestRegressor()
rfmodel.fit(xtrain, yrlabel)   # train['registered']
# xtrain 데이터 변수가 9개 변수로 구성되어있음(x1~x9, y)
# rfmodel.fit(x1~x9, y) => yhat=w1x1 + w2x2 + ... + w9x9 + b
# yhat은 예상되는 registered 값
test['resgistered']=rfmodel.predict(xtest)
test['resgistered'].isnull().sum()

0

In [29]:
rfmodel.fit(xtrain, yclabel)  
test['casual']=rfmodel.predict(xtest)
test['casual'].isnull().sum()

0

In [30]:
test

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,year,month,hour,dayofweek,resgistered,casual
0,2011-01-20 00:00:00,1,0,1,1,10.66,11.365,56,26.0027,2011,1,0,3,8.9,0.9
1,2011-01-20 01:00:00,1,0,1,1,10.66,13.635,56,0.0000,2011,1,1,3,4.5,1.2
2,2011-01-20 02:00:00,1,0,1,1,10.66,13.635,56,0.0000,2011,1,2,3,3.3,2.5
3,2011-01-20 03:00:00,1,0,1,1,10.66,12.880,56,11.0014,2011,1,3,3,2.2,1.8
4,2011-01-20 04:00:00,1,0,1,1,10.66,12.880,56,11.0014,2011,1,4,3,2.3,0.7
5,2011-01-20 05:00:00,1,0,1,1,9.84,11.365,60,15.0013,2011,1,5,3,3.9,0.4
6,2011-01-20 06:00:00,1,0,1,1,9.02,10.605,60,15.0013,2011,1,6,3,37.0,2.4
7,2011-01-20 07:00:00,1,0,1,1,9.02,10.605,55,15.0013,2011,1,7,3,89.3,2.0
8,2011-01-20 08:00:00,1,0,1,1,9.02,10.605,55,19.0012,2011,1,8,3,224.8,6.6
9,2011-01-20 09:00:00,1,0,1,2,9.84,11.365,52,15.0013,2011,1,9,3,121.7,6.0
10,2011-01-20 10:00:00,1,0,1,1,10.66,11.365,48,19.9995,2011,1,10,3,50.6,11.0
11,2011-01-20 11:00:00,1,0,1,2,11.48,13.635,45,11.0014,2011,1,11,3,54.9,10.0
12,2011-01-20 12:00:00,1,0,1,2,12.30,16.665,42,0.0000,2011,1,12,3,70.8,7.0
13,2011-01-20 13:00:00,1,0,1,2,11.48,14.395,45,7.0015,2011,1,13,3,73.8,12.9
14,2011-01-20 14:00:00,1,0,1,2,12.30,15.150,45,8.9981,2011,1,14,3,65.8,11.5
15,2011-01-20 15:00:00,1,0,1,2,13.12,15.910,45,12.9980,2011,1,15,3,63.2,14.2
16,2011-01-20 16:00:00,1,0,1,2,12.30,15.150,49,8.9981,2011,1,16,3,78.4,8.1
17,2011-01-20 17:00:00,1,0,1,2,12.30,15.910,49,7.0015,2011,1,17,3,186.9,9.1
18,2011-01-20 18:00:00,1,0,1,2,10.66,12.880,56,12.9980,2011,1,18,3,153.0,9.2
19,2011-01-20 19:00:00,1,0,1,1,10.66,11.365,56,22.0028,2011,1,19,3,104.1,9.0
20,2011-01-20 20:00:00,1,0,1,2,10.66,12.120,60,19.0012,2011,1,20,3,76.5,6.5
21,2011-01-20 21:00:00,1,0,1,2,9.84,11.365,60,16.9979,2011,1,21,3,44.3,2.7
22,2011-01-20 22:00:00,1,0,1,2,9.84,10.605,65,19.0012,2011,1,22,3,43.5,2.3
23,2011-01-20 23:00:00,1,0,1,2,9.84,10.605,65,22.0028,2011,1,23,3,21.2,2.2
24,2011-01-21 00:00:00,1,0,1,2,9.84,11.365,70,16.9979,2011,1,0,4,12.1,1.8
25,2011-01-21 01:00:00,1,0,1,2,9.84,11.365,70,16.9979,2011,1,1,4,5.2,1.1
26,2011-01-21 02:00:00,1,0,1,3,9.84,12.120,75,11.0014,2011,1,2,4,4.5,0.4
27,2011-01-21 03:00:00,1,0,1,3,9.02,10.605,80,19.9995,2011,1,3,4,0.8,0.2
28,2011-01-21 04:00:00,1,0,1,2,9.02,12.880,87,6.0032,2011,1,4,4,1.4,0.2
29,2011-01-21 05:00:00,1,0,1,1,9.84,9.850,60,27.9993,2011,1,5,4,4.3,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6463,2012-12-30 18:00:00,1,0,0,2,9.84,10.605,44,19.9995,2012,12,18,6,151.4,15.2
6464,2012-12-30 19:00:00,1,0,0,1,13.94,18.180,61,0.0000,2012,12,19,6,162.5,26.8
6465,2012-12-30 20:00:00,1,0,0,1,9.02,9.850,47,22.0028,2012,12,20,6,96.6,6.6
6466,2012-12-30 21:00:00,1,0,0,1,8.20,10.605,51,11.0014,2012,12,21,6,92.1,7.1
6467,2012-12-30 22:00:00,1,0,0,1,8.20,9.850,55,12.9980,2012,12,22,6,69.0,5.1
6468,2012-12-30 23:00:00,1,0,0,1,8.20,9.850,51,15.0013,2012,12,23,6,47.9,4.5
6469,2012-12-31 00:00:00,1,0,1,1,7.38,9.090,55,12.9980,2012,12,0,0,21.9,2.3
6470,2012-12-31 01:00:00,1,0,1,1,7.38,9.090,55,12.9980,2012,12,1,0,11.4,1.2
6471,2012-12-31 02:00:00,1,0,1,1,6.56,8.335,59,11.0014,2012,12,2,0,10.1,0.6
6472,2012-12-31 03:00:00,1,0,1,1,6.56,9.090,59,7.0015,2012,12,3,0,3.6,0.0
6473,2012-12-31 04:00:00,1,0,1,1,5.74,8.335,69,7.0015,2012,12,4,0,7.7,0.1
6474,2012-12-31 05:00:00,1,0,1,1,6.56,7.575,64,12.9980,2012,12,5,0,33.6,0.3
6475,2012-12-31 06:00:00,1,0,1,1,6.56,8.335,64,11.0014,2012,12,6,0,118.8,1.5
6476,2012-12-31 07:00:00,1,0,1,1,6.56,9.090,64,8.9981,2012,12,7,0,317.1,5.3
6477,2012-12-31 08:00:00,1,0,1,1,5.74,7.575,69,8.9981,2012,12,8,0,601.5,11.3
6478,2012-12-31 09:00:00,1,0,1,2,7.38,10.605,64,7.0015,2012,12,9,0,259.3,17.2
6479,2012-12-31 10:00:00,1,0,1,2,8.20,10.605,69,8.9981,2012,12,10,0,162.6,20.7
6480,2012-12-31 11:00:00,1,0,1,2,9.02,11.365,60,12.9980,2012,12,11,0,141.7,18.9
6481,2012-12-31 12:00:00,1,0,1,2,9.84,11.365,56,12.9980,2012,12,12,0,176.2,20.5
6482,2012-12-31 13:00:00,1,0,1,2,10.66,12.880,44,11.0014,2012,12,13,0,169.8,22.4
6483,2012-12-31 14:00:00,1,0,1,2,11.48,13.635,45,15.0013,2012,12,14,0,169.4,24.0
6484,2012-12-31 15:00:00,1,0,1,2,11.48,14.395,45,8.9981,2012,12,15,0,183.1,26.2
6485,2012-12-31 16:00:00,1,0,1,2,10.66,12.880,48,12.9980,2012,12,16,0,276.0,26.1
6486,2012-12-31 17:00:00,1,0,1,2,10.66,14.395,48,6.0032,2012,12,17,0,373.6,25.4
6487,2012-12-31 18:00:00,1,0,1,2,10.66,13.635,48,8.9981,2012,12,18,0,371.8,22.9
6488,2012-12-31 19:00:00,1,0,1,2,10.66,12.880,60,11.0014,2012,12,19,0,229.9,9.4
6489,2012-12-31 20:00:00,1,0,1,2,10.66,12.880,60,11.0014,2012,12,20,0,190.8,7.6
6490,2012-12-31 21:00:00,1,0,1,1,10.66,12.880,60,11.0014,2012,12,21,0,130.0,5.7
6491,2012-12-31 22:00:00,1,0,1,1,10.66,13.635,56,8.9981,2012,12,22,0,93.7,4.6
6492,2012-12-31 23:00:00,1,0,1,1,10.66,13.635,65,8.9981,2012,12,23,0,57.2,2.5