누락값(NaN): NaN, NAN, nan 등으로 일반적인 표기, 누락값을 처리하기 위해 넘파이가 필요함 
* 바구니 조차 없고, 존재하지 않는 값

In [2]:
from numpy import NaN,NAN,nan
import pandas as pd

# 3가지 Nan을 다 데려오겠음

In [3]:
print(NaN == True)
print(NaN == False)
print(NaN == 0)
print(NaN == " ") # 바구니는 있는데 그안에 내용물이 없음
print(NaN == NaN) # 값이 아니므로 비교 자체를 수행 못함
# NaN 자체는 특정 값이 아님

False
False
False
False
False

In [4]:
# isnull: 누락값을 확인하는 메서드 
pd.isnull(NaN)
x=[1,2,3,NaN]
pd.isnull(x)

array([False, False, False,  True])

In [5]:
# notnull: null이 아니다
pd.notnull(10) #10은 누락값이 아니므로 true
pd.notnull("test") #누락값이 아니므로 true
pd.notnull(x)

array([ True,  True,  True, False])

# 누락값이 발생하는 이유
- 1) 누락값이 있는 데이터를 연결할 때 
- 2) 데이터 입력시 누락값이 생길 수 있음
- 3) 범위를 주고 데이터를 추출하고자 할 때
- 4) 누락값이 포함된 변수와 연산을 수행할 때

In [6]:
visited=pd.read_csv("data/survey_visited.csv")
visited

   ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

In [7]:
survey=pd.read_csv("data/survey_survey.csv")
survey

    taken person quant  reading
0     619   dyer   rad     9.82
1     619   dyer   sal     0.13
2     622   dyer   rad     7.80
3     622   dyer   sal     0.09
4     734     pb   rad     8.41
5     734   lake   sal     0.05
6     734     pb  temp   -21.50
7     735     pb   rad     7.22
8     735    NaN   sal     0.06
9     735    NaN  temp   -26.00
10    751     pb   rad     4.35
11    751     pb  temp   -18.50
12    751   lake   sal     0.10
13    752   lake   rad     2.19
14    752   lake   sal     0.09
15    752   lake  temp   -16.00
16    752    roe   sal    41.60
17    837   lake   rad     1.46
18    837   lake   sal     0.21
19    837    roe   sal    22.50
20    844    roe   rad    11.25

In [8]:
vs=visited.merge(survey, left_on="ident", right_on="taken")

In [9]:
vs

    ident   site       dated  taken person quant  reading
0     619   DR-1  1927-02-08    619   dyer   rad     9.82
1     619   DR-1  1927-02-08    619   dyer   sal     0.13
2     622   DR-1  1927-02-10    622   dyer   rad     7.80
3     622   DR-1  1927-02-10    622   dyer   sal     0.09
4     734   DR-3  1939-01-07    734     pb   rad     8.41
5     734   DR-3  1939-01-07    734   lake   sal     0.05
6     734   DR-3  1939-01-07    734     pb  temp   -21.50
7     735   DR-3  1930-01-12    735     pb   rad     7.22
8     735   DR-3  1930-01-12    735    NaN   sal     0.06
9     735   DR-3  1930-01-12    735    NaN  temp   -26.00
10    751   DR-3  1930-02-26    751     pb   rad     4.35
11    751   DR-3  1930-02-26    751     pb  temp   -18.50
12    751   DR-3  1930-02-26    751   lake   sal     0.10
13    752   DR-3         NaN    752   lake   rad     2.19
14    752   DR-3         NaN    752   lake   sal     0.09
15    752   DR-3         NaN    752   lake  temp   -16.00
16    752   DR-3         NaN    752    roe   sal    41.60
17    837  MSK-4  1932-01-14    837   lake   rad     1.46
18    837  MSK-4  1932-01-14    837   lake   sal     0.21
19    837  MSK-4  1932-01-14    837    roe   sal    22.50
20    844   DR-1  1932-03-22    844    roe   rad    11.25

In [10]:
num_legs=pd.Series({
    'goat':4,
    'amoeba':nan    
})
# 원래 없는 경우가 있을 수 이씅ㅁ

In [11]:
num_legs

goat      4.0
amoeba    NaN
dtype: float64

In [12]:
gapminder=pd.read_csv("Downloads\data/gapminder.tsv", sep="\t")

FileNotFoundError: File b'Downloads\\data/gapminder.tsv' does not exist

In [13]:
gapminder

NameError: name 'gapminder' is not defined

In [14]:
# 연도별로 그룹화한 다음 lifeExp 컬럼의 평균
life_exp=gapminder.groupby(['year'])['lifeExp'].mean()
life_exp

NameError: name 'gapminder' is not defined

In [74]:
# 2000~2009까지 데이터를 추출(range함수 이용)

life_exp.loc[range(2000,2010)],

C:\Users\B-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  This is separate from the ipykernel package so we can avoid doing imports until

(year
 2000          NaN
 2001          NaN
 2002    65.694923
 2003          NaN
 2004          NaN
 2005          NaN
 2006          NaN
 2007    67.007423
 2008          NaN
 2009          NaN
 Name: lifeExp, dtype: float64,)

In [76]:
life_exp.loc[[2002]]

year
2002    65.694923
Name: lifeExp, dtype: float64

In [77]:
life_exp.loc[[2002,2007]]

year
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [81]:
y2000=life_exp[life_exp.index>2000]
y2000

year
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64






------------------------------------------------------------------------------------

In [90]:
ebola=pd.read_csv("data/country_timeseries.csv")
ebola.index
ebola.columns
ebola.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 18 columns):
Date                   122 non-null object
Day                    122 non-null int64
Cases_Guinea           93 non-null float64
Cases_Liberia          83 non-null float64
Cases_SierraLeone      87 non-null float64
Cases_Nigeria          38 non-null float64
Cases_Senegal          25 non-null float64
Cases_UnitedStates     18 non-null float64
Cases_Spain            16 non-null float64
Cases_Mali             12 non-null float64
Deaths_Guinea          92 non-null float64
Deaths_Liberia         81 non-null float64
Deaths_SierraLeone     87 non-null float64
Deaths_Nigeria         38 non-null float64
Deaths_Senegal         22 non-null float64
Deaths_UnitedStates    18 non-null float64
Deaths_Spain           16 non-null float64
Deaths_Mali            12 non-null float64
dtypes: float64(16), int64(1), object(1)
memory usage: 17.2+ KB

In [95]:
ebola.count()#누락값이 아닌 개수
ebola.shape # (122, 18) => 행, 렬
ebola.shape[0]-ebola.count() # 누락값의 개수(NaN의 개수)

Date                     0
Day                      0
Cases_Guinea            29
Cases_Liberia           39
Cases_SierraLeone       35
Cases_Nigeria           84
Cases_Senegal           97
Cases_UnitedStates     104
Cases_Spain            106
Cases_Mali             110
Deaths_Guinea           30
Deaths_Liberia          41
Deaths_SierraLeone      35
Deaths_Nigeria          84
Deaths_Senegal         100
Deaths_UnitedStates    104
Deaths_Spain           106
Deaths_Mali            110
dtype: int64

In [109]:
import numpy as np

ebola.isnull()

np.count_nonzero(ebola.isnull()) #nonzero : 0(False)이 아닌것
# count_nonzero:0(False)가 아닌 값들의 개수를 세는 함수

cnt_nan=122*18-np.count_nonzero(ebola.isnull())
np.count_nonzero(ebola.isnull())

# ebola.isnull():null이면 True, 아니면 False
# count_nonzero:0이 아닌 것의 개수 1(True)의 개수

1214

In [111]:
ebola['Cases_Guinea'].count() # 122 중 nan이 아닌 개수: 93건

93

In [116]:
ebola['Cases_Guinea'].isnull() #nan이면 true
np.count_nonzero(ebola['Cases_Guinea'].isnull()) #True(1)의 개수가 몇개임?

29

In [126]:
ebola.Cases_Guinea
ebola.Cases_Guinea.value_counts() #각각의 값들의 개수(Nan은 제외)
ebola.Cases_Guinea.value_counts(dropna=True) #dropna>nan을 제거한 나머지
#NaN은 제외, 디폴트값이
ebola.Cases_Guinea.value_counts(dropna=False) #nan 포함
ebola.Cases_Guinea.value_counts(dropna=False).head() #상위 다섯개 뽑겠음

NaN       29
 86.0      3
 495.0     2
 112.0     2
 390.0     2
Name: Cases_Guinea, dtype: int64

In [129]:
# fillna(): 특정값으로 na를 대체
ebola.fillna(0) # nan을 0으로 대체
ebola.fillna(0).iloc[0:10, 0:5] # 10행 5열로 출력

         Date  Day  Cases_Guinea  Cases_Liberia  Cases_SierraLeone
0    1/5/2015  289        2776.0            0.0            10030.0
1    1/4/2015  288        2775.0            0.0             9780.0
2    1/3/2015  287        2769.0         8166.0             9722.0
3    1/2/2015  286           0.0         8157.0                0.0
4  12/31/2014  284        2730.0         8115.0             9633.0
5  12/28/2014  281        2706.0         8018.0             9446.0
6  12/27/2014  280        2695.0            0.0             9409.0
7  12/24/2014  277        2630.0         7977.0             9203.0
8  12/21/2014  273        2597.0            0.0             9004.0
9  12/20/2014  272        2571.0         7862.0             8939.0

In [134]:
# ebola
ebola.fillna(method="ffill")
# 순방향(위에서 아래로)으로 이동해가면서 NaN을 만나게 되면,
# 직전에(위) 있는 데이터 값으로 NaN을 대체

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,2769.0,8157.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN
5,12/28/2014,281,2706.0,8018.0,9446.0,NaN,NaN,NaN,NaN,NaN,1708.0,3423.0,2758.0,NaN,NaN,NaN,NaN,NaN
6,12/27/2014,280,2695.0,8018.0,9409.0,NaN,NaN,NaN,NaN,NaN,1697.0,3423.0,2732.0,NaN,NaN,NaN,NaN,NaN
7,12/24/2014,277,2630.0,7977.0,9203.0,NaN,NaN,NaN,NaN,NaN,1697.0,3413.0,2655.0,NaN,NaN,NaN,NaN,NaN
8,12/21/2014,273,2597.0,7977.0,9004.0,NaN,NaN,NaN,NaN,NaN,1607.0,3413.0,2582.0,NaN,NaN,NaN,NaN,NaN
9,12/20/2014,272,2571.0,7862.0,8939.0,NaN,NaN,NaN,NaN,NaN,1586.0,3384.0,2556.0,NaN,NaN,NaN,NaN,NaN
10,12/18/2014,271,2571.0,7830.0,8939.0,NaN,NaN,NaN,NaN,NaN,1586.0,3376.0,2556.0,NaN,NaN,NaN,NaN,NaN
11,12/14/2014,267,2416.0,7830.0,8356.0,NaN,NaN,NaN,NaN,NaN,1525.0,3376.0,2085.0,NaN,NaN,NaN,NaN,NaN
12,12/9/2014,262,2416.0,7797.0,8356.0,NaN,NaN,NaN,NaN,NaN,1525.0,3290.0,2085.0,NaN,NaN,NaN,NaN,NaN
13,12/7/2014,260,2292.0,7797.0,7897.0,20.0,1.0,4.0,1.0,7.0,1428.0,3290.0,1768.0,8.0,0.0,1.0,0.0,6.0
14,12/3/2014,256,2292.0,7719.0,7897.0,20.0,1.0,4.0,1.0,7.0,1428.0,3177.0,1768.0,8.0,0.0,1.0,0.0,6.0
15,11/30/2014,253,2164.0,7719.0,7312.0,20.0,1.0,4.0,1.0,7.0,1327.0,3177.0,1583.0,8.0,0.0,1.0,0.0,6.0
16,11/28/2014,251,2164.0,7635.0,7312.0,20.0,1.0,4.0,1.0,7.0,1327.0,3145.0,1583.0,8.0,0.0,1.0,0.0,6.0
17,11/23/2014,246,2134.0,7635.0,6599.0,20.0,1.0,4.0,1.0,7.0,1260.0,3145.0,1398.0,8.0,0.0,1.0,0.0,6.0
18,11/22/2014,245,2134.0,7168.0,6599.0,20.0,1.0,4.0,1.0,7.0,1260.0,3016.0,1398.0,8.0,0.0,1.0,0.0,6.0
19,11/18/2014,241,2047.0,7082.0,6190.0,20.0,1.0,4.0,1.0,6.0,1214.0,2963.0,1267.0,8.0,0.0,1.0,0.0,6.0
20,11/16/2014,239,1971.0,7082.0,6073.0,20.0,1.0,4.0,1.0,5.0,1192.0,2963.0,1250.0,8.0,0.0,1.0,0.0,5.0
21,11/15/2014,238,1971.0,7069.0,6073.0,20.0,1.0,4.0,1.0,5.0,1192.0,2964.0,1250.0,8.0,0.0,1.0,0.0,5.0
22,11/11/2014,234,1919.0,7069.0,5586.0,20.0,1.0,4.0,1.0,4.0,1166.0,2964.0,1187.0,8.0,0.0,1.0,0.0,3.0
23,11/10/2014,233,1919.0,6878.0,5586.0,20.0,1.0,4.0,1.0,4.0,1166.0,2812.0,1187.0,8.0,0.0,1.0,0.0,3.0
24,11/9/2014,232,1878.0,6878.0,5368.0,20.0,1.0,4.0,1.0,1.0,1142.0,2812.0,1169.0,8.0,0.0,1.0,0.0,1.0
25,11/8/2014,231,1878.0,6822.0,5368.0,20.0,1.0,4.0,1.0,1.0,1142.0,2836.0,1169.0,8.0,0.0,1.0,0.0,1.0
26,11/4/2014,227,1878.0,6619.0,4862.0,20.0,1.0,4.0,1.0,1.0,1142.0,2766.0,1130.0,8.0,0.0,1.0,0.0,1.0
27,11/3/2014,226,1760.0,6619.0,4862.0,20.0,1.0,4.0,1.0,1.0,1054.0,2766.0,1130.0,8.0,0.0,1.0,0.0,1.0
28,11/2/2014,225,1731.0,6619.0,4759.0,20.0,1.0,4.0,1.0,1.0,1041.0,2766.0,1070.0,8.0,0.0,1.0,0.0,1.0
29,10/31/2014,222,1731.0,6525.0,4759.0,20.0,1.0,4.0,1.0,1.0,1041.0,2697.0,1070.0,8.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,5/23/2014,62,258.0,12.0,0.0,0.0,1.0,1.0,1.0,1.0,174.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
93,5/12/2014,51,248.0,12.0,0.0,0.0,1.0,1.0,1.0,1.0,171.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
94,5/10/2014,49,233.0,12.0,0.0,0.0,1.0,1.0,1.0,1.0,157.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
95,5/7/2014,46,236.0,13.0,0.0,0.0,1.0,1.0,1.0,1.0,158.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
96,5/5/2014,44,235.0,13.0,0.0,0.0,1.0,1.0,1.0,1.0,157.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
97,5/3/2014,42,231.0,13.0,0.0,0.0,1.0,1.0,1.0,1.0,155.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
98,5/1/2014,40,226.0,13.0,0.0,0.0,1.0,1.0,1.0,1.0,149.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
99,4/26/2014,35,224.0,13.0,0.0,0.0,1.0,1.0,1.0,1.0,143.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
100,4/24/2014,33,224.0,35.0,0.0,0.0,1.0,1.0,1.0,1.0,143.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
101,4/23/2014,32,218.0,35.0,0.0,0.0,1.0,1.0,1.0,1.0,141.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
102,4/22/2014,31,218.0,35.0,0.0,0.0,1.0,1.0,1.0,1.0,141.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
103,4/21/2014,30,218.0,34.0,0.0,0.0,1.0,1.0,1.0,1.0,141.0,11.0,0.0,0.0,0.0,0.0,1.0,1.0
104,4/20/2014,29,208.0,34.0,0.0,0.0,1.0,1.0,1.0,1.0,136.0,6.0,0.0,0.0,0.0,0.0,1.0,1.0
105,4/17/2014,26,203.0,27.0,0.0,0.0,1.0,1.0,1.0,1.0,129.0,6.0,0.0,0.0,0.0,0.0,1.0,1.0
106,4/16/2014,25,197.0,27.0,0.0,0.0,1.0,1.0,1.0,1.0,122.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0
107,4/15/2014,24,197.0,27.0,12.0,0.0,1.0,1.0,1.0,1.0,122.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0
108,4/14/2014,23,168.0,27.0,12.0,0.0,1.0,1.0,1.0,1.0,108.0,13.0,0.0,0.0,0.0,0.0,1.0,1.0
109,4/11/2014,20,159.0,26.0,2.0,0.0,1.0,1.0,1.0,1.0,106.0,13.0,2.0,0.0,0.0,0.0,1.0,1.0
110,4/9/2014,18,158.0,25.0,2.0,0.0,1.0,1.0,1.0,1.0,101.0,12.0,2.0,0.0,0.0,0.0,1.0,1.0
111,4/7/2014,16,151.0,21.0,2.0,0.0,1.0,1.0,1.0,1.0,95.0,10.0,2.0,0.0,0.0,0.0,1.0,1.0
112,4/4/2014,13,143.0,18.0,2.0,0.0,1.0,1.0,1.0,1.0,86.0,7.0,2.0,0.0,0.0,0.0,1.0,1.0
113,4/1/2014,10,127.0,8.0,2.0,0.0,1.0,1.0,1.0,1.0,83.0,5.0,2.0,0.0,0.0,0.0,1.0,1.0
114,3/31/2014,9,122.0,8.0,2.0,0.0,1.0,1.0,1.0,1.0,80.0,4.0,2.0,0.0,0.0,0.0,1.0,1.0
115,3/29/2014,7,112.0,7.0,2.0,0.0,1.0,1.0,1.0,1.0,70.0,2.0,2.0,0.0,0.0,0.0,1.0,1.0
116,3/28/2014,6,112.0,3.0,2.0,0.0,1.0,1.0,1.0,1.0,70.0,3.0,2.0,0.0,0.0,0.0,1.0,1.0
117,3/27/2014,5,103.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,66.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
118,3/26/2014,4,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,62.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
119,3/25/2014,3,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,60.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
120,3/24/2014,2,86.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,59.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0
121,3/22/2014,0,49.0,8.0,6.0,0.0,1.0,1.0,1.0,1.0,29.0,6.0,5.0,0.0,0.0,0.0,1.0,1.0

In [136]:
ebola.fillna(method="bfill")
# 바로 밑에 있는 데이터 값으로 NaN을 대체

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,8166.0,10030.0,20.0,1.0,4.0,1.0,7.0,1786.0,3496.0,2977.0,8.0,0.0,1.0,0.0,6.0
1,1/4/2015,288,2775.0,8166.0,9780.0,20.0,1.0,4.0,1.0,7.0,1781.0,3496.0,2943.0,8.0,0.0,1.0,0.0,6.0
2,1/3/2015,287,2769.0,8166.0,9722.0,20.0,1.0,4.0,1.0,7.0,1767.0,3496.0,2915.0,8.0,0.0,1.0,0.0,6.0
3,1/2/2015,286,2730.0,8157.0,9633.0,20.0,1.0,4.0,1.0,7.0,1739.0,3496.0,2827.0,8.0,0.0,1.0,0.0,6.0
4,12/31/2014,284,2730.0,8115.0,9633.0,20.0,1.0,4.0,1.0,7.0,1739.0,3471.0,2827.0,8.0,0.0,1.0,0.0,6.0
5,12/28/2014,281,2706.0,8018.0,9446.0,20.0,1.0,4.0,1.0,7.0,1708.0,3423.0,2758.0,8.0,0.0,1.0,0.0,6.0
6,12/27/2014,280,2695.0,7977.0,9409.0,20.0,1.0,4.0,1.0,7.0,1697.0,3413.0,2732.0,8.0,0.0,1.0,0.0,6.0
7,12/24/2014,277,2630.0,7977.0,9203.0,20.0,1.0,4.0,1.0,7.0,1607.0,3413.0,2655.0,8.0,0.0,1.0,0.0,6.0
8,12/21/2014,273,2597.0,7862.0,9004.0,20.0,1.0,4.0,1.0,7.0,1607.0,3384.0,2582.0,8.0,0.0,1.0,0.0,6.0
9,12/20/2014,272,2571.0,7862.0,8939.0,20.0,1.0,4.0,1.0,7.0,1586.0,3384.0,2556.0,8.0,0.0,1.0,0.0,6.0
10,12/18/2014,271,2416.0,7830.0,8356.0,20.0,1.0,4.0,1.0,7.0,1525.0,3376.0,2085.0,8.0,0.0,1.0,0.0,6.0
11,12/14/2014,267,2416.0,7797.0,8356.0,20.0,1.0,4.0,1.0,7.0,1525.0,3290.0,2085.0,8.0,0.0,1.0,0.0,6.0
12,12/9/2014,262,2292.0,7797.0,7897.0,20.0,1.0,4.0,1.0,7.0,1428.0,3290.0,1768.0,8.0,0.0,1.0,0.0,6.0
13,12/7/2014,260,2292.0,7719.0,7897.0,20.0,1.0,4.0,1.0,7.0,1428.0,3177.0,1768.0,8.0,0.0,1.0,0.0,6.0
14,12/3/2014,256,2164.0,7719.0,7312.0,20.0,1.0,4.0,1.0,7.0,1327.0,3177.0,1583.0,8.0,0.0,1.0,0.0,6.0
15,11/30/2014,253,2164.0,7635.0,7312.0,20.0,1.0,4.0,1.0,7.0,1327.0,3145.0,1583.0,8.0,0.0,1.0,0.0,6.0
16,11/28/2014,251,2134.0,7635.0,6599.0,20.0,1.0,4.0,1.0,7.0,1260.0,3145.0,1398.0,8.0,0.0,1.0,0.0,6.0
17,11/23/2014,246,2134.0,7168.0,6599.0,20.0,1.0,4.0,1.0,7.0,1260.0,3016.0,1398.0,8.0,0.0,1.0,0.0,6.0
18,11/22/2014,245,2047.0,7168.0,6190.0,20.0,1.0,4.0,1.0,6.0,1214.0,3016.0,1267.0,8.0,0.0,1.0,0.0,6.0
19,11/18/2014,241,2047.0,7082.0,6190.0,20.0,1.0,4.0,1.0,6.0,1214.0,2963.0,1267.0,8.0,0.0,1.0,0.0,6.0
20,11/16/2014,239,1971.0,7069.0,6073.0,20.0,1.0,4.0,1.0,5.0,1192.0,2964.0,1250.0,8.0,0.0,1.0,0.0,5.0
21,11/15/2014,238,1919.0,7069.0,5586.0,20.0,1.0,4.0,1.0,4.0,1166.0,2964.0,1187.0,8.0,0.0,1.0,0.0,3.0
22,11/11/2014,234,1919.0,6878.0,5586.0,20.0,1.0,4.0,1.0,4.0,1166.0,2812.0,1187.0,8.0,0.0,1.0,0.0,3.0
23,11/10/2014,233,1878.0,6878.0,5368.0,20.0,1.0,4.0,1.0,1.0,1142.0,2812.0,1169.0,8.0,0.0,1.0,0.0,1.0
24,11/9/2014,232,1878.0,6822.0,5368.0,20.0,1.0,4.0,1.0,1.0,1142.0,2836.0,1169.0,8.0,0.0,1.0,0.0,1.0
25,11/8/2014,231,1760.0,6822.0,4862.0,20.0,1.0,4.0,1.0,1.0,1054.0,2836.0,1130.0,8.0,0.0,1.0,0.0,1.0
26,11/4/2014,227,1760.0,6619.0,4862.0,20.0,1.0,4.0,1.0,1.0,1054.0,2766.0,1130.0,8.0,0.0,1.0,0.0,1.0
27,11/3/2014,226,1760.0,6525.0,4759.0,20.0,1.0,4.0,1.0,1.0,1054.0,2697.0,1070.0,8.0,0.0,1.0,0.0,1.0
28,11/2/2014,225,1731.0,6525.0,4759.0,20.0,1.0,4.0,1.0,1.0,1041.0,2697.0,1070.0,8.0,0.0,1.0,0.0,1.0
29,10/31/2014,222,1667.0,6525.0,5338.0,20.0,1.0,4.0,1.0,1.0,1018.0,2697.0,1510.0,8.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,5/23/2014,62,258.0,12.0,0.0,NaN,NaN,NaN,NaN,NaN,174.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
93,5/12/2014,51,248.0,12.0,0.0,NaN,NaN,NaN,NaN,NaN,171.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
94,5/10/2014,49,233.0,12.0,0.0,NaN,NaN,NaN,NaN,NaN,157.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
95,5/7/2014,46,236.0,13.0,0.0,NaN,NaN,NaN,NaN,NaN,158.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
96,5/5/2014,44,235.0,13.0,0.0,NaN,NaN,NaN,NaN,NaN,157.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
97,5/3/2014,42,231.0,13.0,0.0,NaN,NaN,NaN,NaN,NaN,155.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
98,5/1/2014,40,226.0,13.0,0.0,NaN,NaN,NaN,NaN,NaN,149.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
99,4/26/2014,35,224.0,35.0,0.0,NaN,NaN,NaN,NaN,NaN,143.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
100,4/24/2014,33,218.0,35.0,0.0,NaN,NaN,NaN,NaN,NaN,141.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
101,4/23/2014,32,218.0,34.0,0.0,NaN,NaN,NaN,NaN,NaN,141.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
102,4/22/2014,31,208.0,34.0,0.0,NaN,NaN,NaN,NaN,NaN,136.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
103,4/21/2014,30,208.0,34.0,12.0,NaN,NaN,NaN,NaN,NaN,136.0,11.0,2.0,NaN,NaN,NaN,NaN,NaN
104,4/20/2014,29,208.0,27.0,12.0,NaN,NaN,NaN,NaN,NaN,136.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN
105,4/17/2014,26,203.0,27.0,12.0,NaN,NaN,NaN,NaN,NaN,129.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN
106,4/16/2014,25,197.0,27.0,12.0,NaN,NaN,NaN,NaN,NaN,122.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN
107,4/15/2014,24,168.0,26.0,12.0,NaN,NaN,NaN,NaN,NaN,108.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN
108,4/14/2014,23,168.0,26.0,2.0,NaN,NaN,NaN,NaN,NaN,108.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN
109,4/11/2014,20,159.0,26.0,2.0,NaN,NaN,NaN,NaN,NaN,106.0,13.0,2.0,NaN,NaN,NaN,NaN,NaN
110,4/9/2014,18,158.0,25.0,2.0,NaN,NaN,NaN,NaN,NaN,101.0,12.0,2.0,NaN,NaN,NaN,NaN,NaN
111,4/7/2014,16,151.0,21.0,2.0,NaN,NaN,NaN,NaN,NaN,95.0,10.0,2.0,NaN,NaN,NaN,NaN,NaN
112,4/4/2014,13,143.0,18.0,2.0,NaN,NaN,NaN,NaN,NaN,86.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN
113,4/1/2014,10,127.0,8.0,2.0,NaN,NaN,NaN,NaN,NaN,83.0,5.0,2.0,NaN,NaN,NaN,NaN,NaN
114,3/31/2014,9,122.0,8.0,2.0,NaN,NaN,NaN,NaN,NaN,80.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN
115,3/29/2014,7,112.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,70.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
116,3/28/2014,6,112.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,70.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN
117,3/27/2014,5,103.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,66.0,6.0,5.0,NaN,NaN,NaN,NaN,NaN
118,3/26/2014,4,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,3/25/2014,3,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,3/24/2014,2,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,3/22/2014,0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
# ebola
# ebola.interpolate() 위아래 중간값을 구함

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.000000,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.000000,NaN,2977.000000,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.000000,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.000000,NaN,2943.000000,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.000000,8166.000000,9722.0,NaN,NaN,NaN,NaN,NaN,1767.000000,3496.0,2915.000000,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,2749.500000,8157.000000,9677.5,NaN,NaN,NaN,NaN,NaN,1753.000000,3496.0,2871.000000,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.000000,8115.000000,9633.0,NaN,NaN,NaN,NaN,NaN,1739.000000,3471.0,2827.000000,NaN,NaN,NaN,NaN,NaN
5,12/28/2014,281,2706.000000,8018.000000,9446.0,NaN,NaN,NaN,NaN,NaN,1708.000000,3423.0,2758.000000,NaN,NaN,NaN,NaN,NaN
6,12/27/2014,280,2695.000000,7997.500000,9409.0,NaN,NaN,NaN,NaN,NaN,1697.000000,3418.0,2732.000000,NaN,NaN,NaN,NaN,NaN
7,12/24/2014,277,2630.000000,7977.000000,9203.0,NaN,NaN,NaN,NaN,NaN,1652.000000,3413.0,2655.000000,NaN,NaN,NaN,NaN,NaN
8,12/21/2014,273,2597.000000,7919.500000,9004.0,NaN,NaN,NaN,NaN,NaN,1607.000000,3398.5,2582.000000,NaN,NaN,NaN,NaN,NaN
9,12/20/2014,272,2571.000000,7862.000000,8939.0,NaN,NaN,NaN,NaN,NaN,1586.000000,3384.0,2556.000000,NaN,NaN,NaN,NaN,NaN
10,12/18/2014,271,2493.500000,7830.000000,8647.5,NaN,NaN,NaN,NaN,NaN,1555.500000,3376.0,2320.500000,NaN,NaN,NaN,NaN,NaN
11,12/14/2014,267,2416.000000,7813.500000,8356.0,NaN,NaN,NaN,NaN,NaN,1525.000000,3333.0,2085.000000,NaN,NaN,NaN,NaN,NaN
12,12/9/2014,262,2354.000000,7797.000000,8126.5,NaN,NaN,NaN,NaN,NaN,1476.500000,3290.0,1926.500000,NaN,NaN,NaN,NaN,NaN
13,12/7/2014,260,2292.000000,7758.000000,7897.0,20.0,1.0,4.0,1.0,7.0,1428.000000,3233.5,1768.000000,8.0,0.0,1.0,0.0,6.0
14,12/3/2014,256,2228.000000,7719.000000,7604.5,20.0,1.0,4.0,1.0,7.0,1377.500000,3177.0,1675.500000,8.0,0.0,1.0,0.0,6.0
15,11/30/2014,253,2164.000000,7677.000000,7312.0,20.0,1.0,4.0,1.0,7.0,1327.000000,3161.0,1583.000000,8.0,0.0,1.0,0.0,6.0
16,11/28/2014,251,2149.000000,7635.000000,6955.5,20.0,1.0,4.0,1.0,7.0,1293.500000,3145.0,1490.500000,8.0,0.0,1.0,0.0,6.0
17,11/23/2014,246,2134.000000,7401.500000,6599.0,20.0,1.0,4.0,1.0,7.0,1260.000000,3080.5,1398.000000,8.0,0.0,1.0,0.0,6.0
18,11/22/2014,245,2090.500000,7168.000000,6394.5,20.0,1.0,4.0,1.0,6.5,1237.000000,3016.0,1332.500000,8.0,0.0,1.0,0.0,6.0
19,11/18/2014,241,2047.000000,7082.000000,6190.0,20.0,1.0,4.0,1.0,6.0,1214.000000,2963.0,1267.000000,8.0,0.0,1.0,0.0,6.0
20,11/16/2014,239,1971.000000,7075.500000,6073.0,20.0,1.0,4.0,1.0,5.0,1192.000000,2963.5,1250.000000,8.0,0.0,1.0,0.0,5.0
21,11/15/2014,238,1945.000000,7069.000000,5829.5,20.0,1.0,4.0,1.0,4.5,1179.000000,2964.0,1218.500000,8.0,0.0,1.0,0.0,4.0
22,11/11/2014,234,1919.000000,6973.500000,5586.0,20.0,1.0,4.0,1.0,4.0,1166.000000,2888.0,1187.000000,8.0,0.0,1.0,0.0,3.0
23,11/10/2014,233,1898.500000,6878.000000,5477.0,20.0,1.0,4.0,1.0,2.5,1154.000000,2812.0,1178.000000,8.0,0.0,1.0,0.0,2.0
24,11/9/2014,232,1878.000000,6850.000000,5368.0,20.0,1.0,4.0,1.0,1.0,1142.000000,2824.0,1169.000000,8.0,0.0,1.0,0.0,1.0
25,11/8/2014,231,1838.666667,6822.000000,5115.0,20.0,1.0,4.0,1.0,1.0,1112.666667,2836.0,1149.500000,8.0,0.0,1.0,0.0,1.0
26,11/4/2014,227,1799.333333,6619.000000,4862.0,20.0,1.0,4.0,1.0,1.0,1083.333333,2766.0,1130.000000,8.0,0.0,1.0,0.0,1.0
27,11/3/2014,226,1760.000000,6587.666667,4810.5,20.0,1.0,4.0,1.0,1.0,1054.000000,2743.0,1100.000000,8.0,0.0,1.0,0.0,1.0
28,11/2/2014,225,1731.000000,6556.333333,4759.0,20.0,1.0,4.0,1.0,1.0,1041.000000,2720.0,1070.000000,8.0,0.0,1.0,0.0,1.0
29,10/31/2014,222,1699.000000,6525.000000,5048.5,20.0,1.0,4.0,1.0,1.0,1029.500000,2697.0,1290.000000,8.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,5/23/2014,62,258.000000,12.000000,0.0,0.0,1.0,1.0,1.0,1.0,174.000000,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
93,5/12/2014,51,248.000000,12.000000,0.0,0.0,1.0,1.0,1.0,1.0,171.000000,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
94,5/10/2014,49,233.000000,12.000000,0.0,0.0,1.0,1.0,1.0,1.0,157.000000,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
95,5/7/2014,46,236.000000,13.000000,0.0,0.0,1.0,1.0,1.0,1.0,158.000000,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
96,5/5/2014,44,235.000000,13.000000,0.0,0.0,1.0,1.0,1.0,1.0,157.000000,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
97,5/3/2014,42,231.000000,13.000000,0.0,0.0,1.0,1.0,1.0,1.0,155.000000,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
98,5/1/2014,40,226.000000,13.000000,0.0,0.0,1.0,1.0,1.0,1.0,149.000000,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
99,4/26/2014,35,224.000000,24.000000,0.0,0.0,1.0,1.0,1.0,1.0,143.000000,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
100,4/24/2014,33,221.000000,35.000000,0.0,0.0,1.0,1.0,1.0,1.0,142.000000,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
101,4/23/2014,32,218.000000,34.666667,0.0,0.0,1.0,1.0,1.0,1.0,141.000000,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
102,4/22/2014,31,214.666667,34.333333,0.0,0.0,1.0,1.0,1.0,1.0,139.333333,11.0,0.000000,0.0,0.0,0.0,1.0,1.0
103,4/21/2014,30,211.333333,34.000000,2.4,0.0,1.0,1.0,1.0,1.0,137.666667,11.0,0.285714,0.0,0.0,0.0,1.0,1.0
104,4/20/2014,29,208.000000,30.500000,4.8,0.0,1.0,1.0,1.0,1.0,136.000000,6.0,0.571429,0.0,0.0,0.0,1.0,1.0
105,4/17/2014,26,203.000000,27.000000,7.2,0.0,1.0,1.0,1.0,1.0,129.000000,9.5,0.857143,0.0,0.0,0.0,1.0,1.0
106,4/16/2014,25,197.000000,27.000000,9.6,0.0,1.0,1.0,1.0,1.0,122.000000,13.0,1.142857,0.0,0.0,0.0,1.0,1.0
107,4/15/2014,24,182.500000,26.666667,12.0,0.0,1.0,1.0,1.0,1.0,115.000000,13.0,1.428571,0.0,0.0,0.0,1.0,1.0
108,4/14/2014,23,168.000000,26.333333,7.0,0.0,1.0,1.0,1.0,1.0,108.000000,13.0,1.714286,0.0,0.0,0.0,1.0,1.0
109,4/11/2014,20,159.000000,26.000000,2.0,0.0,1.0,1.0,1.0,1.0,106.000000,13.0,2.000000,0.0,0.0,0.0,1.0,1.0
110,4/9/2014,18,158.000000,25.000000,2.0,0.0,1.0,1.0,1.0,1.0,101.000000,12.0,2.000000,0.0,0.0,0.0,1.0,1.0
111,4/7/2014,16,151.000000,21.000000,2.0,0.0,1.0,1.0,1.0,1.0,95.000000,10.0,2.000000,0.0,0.0,0.0,1.0,1.0
112,4/4/2014,13,143.000000,18.000000,2.0,0.0,1.0,1.0,1.0,1.0,86.000000,7.0,2.000000,0.0,0.0,0.0,1.0,1.0
113,4/1/2014,10,127.000000,8.000000,2.0,0.0,1.0,1.0,1.0,1.0,83.000000,5.0,2.000000,0.0,0.0,0.0,1.0,1.0
114,3/31/2014,9,122.000000,8.000000,2.0,0.0,1.0,1.0,1.0,1.0,80.000000,4.0,2.000000,0.0,0.0,0.0,1.0,1.0
115,3/29/2014,7,112.000000,7.000000,2.0,0.0,1.0,1.0,1.0,1.0,70.000000,2.0,2.000000,0.0,0.0,0.0,1.0,1.0
116,3/28/2014,6,112.000000,3.000000,2.0,0.0,1.0,1.0,1.0,1.0,70.000000,3.0,2.000000,0.0,0.0,0.0,1.0,1.0
117,3/27/2014,5,103.000000,8.000000,6.0,0.0,1.0,1.0,1.0,1.0,66.000000,6.0,5.000000,0.0,0.0,0.0,1.0,1.0
118,3/26/2014,4,86.000000,8.000000,6.0,0.0,1.0,1.0,1.0,1.0,62.000000,6.0,5.000000,0.0,0.0,0.0,1.0,1.0
119,3/25/2014,3,86.000000,8.000000,6.0,0.0,1.0,1.0,1.0,1.0,60.000000,6.0,5.000000,0.0,0.0,0.0,1.0,1.0
120,3/24/2014,2,86.000000,8.000000,6.0,0.0,1.0,1.0,1.0,1.0,59.000000,6.0,5.000000,0.0,0.0,0.0,1.0,1.0
121,3/22/2014,0,49.000000,8.000000,6.0,0.0,1.0,1.0,1.0,1.0,29.000000,6.0,5.000000,0.0,0.0,0.0,1.0,1.0